
# Settings regarding the redis-request-broker
rrb:
  queues:
    log: log # Will listen to this queue for saving logs
    get: get # Will listen to this queue for requesting logs
  redis:
    prefix: logging
    port: 6379

# logging targets
# Following targets are available: console, mongodb, cache, telegram.
# More info about the configuration options for each target in the readme.
targets: 
  - type: console
    enabled: true
    level: info
    timestamp: HH:mm:ss.SSS
    indentation: "   ] "
  - type: cache
    enabled: true
    level: debug
    size: 1000
    name: default
  - type: mongodb
    enabled: true
    level: info
  - type: file
    enabled: true
    level: info
    path: logs
    format: Y-MM-DD
    extension: log
  - type: telegram
    enabled: true
    level: warning
    botToken: 123abc
    chats:
      - 123

# Defines the log levels
levels:
  # Defines the hierarchy of the log levels
  # The lower the number the more important the log
  hierarchy:
    error: 0
    warning: 1
    notice: 2
    info: 3
    debug: 4
  # Maps log levels spcified in a request to log levels as defined in hierarchy
  mapping:
    error: error
    err: error
    warning: warning
    wrn: warning
    notice: notice
    ntc: notice
    info: info
    inf: info
    debug: debug
    dbg: debug
  
  # For logs that will be created when something goes wrong internally 
  internal:
    # When an invalid log has been requested (invalid level or title)
    onInvalidLog: warning
    # When a target fails to handle a log 
    onTargetFailedToHandle: warning

# The time a logging target should remain inactive when it fails in ms
targetErrorTimeout: 300_000